apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      restartPolicy: Always
      containers:
      - name: telegraf
        image: telegraf
        imagePullPolicy: Never
        ports:
          - containerPort: 8125
            name: telegraf
        env:
        - name: USER
          value: admin
        - name: PASSWORD
          value: password