# OS
FROM	alpine:3.12

# Update and install
RUN		apk update
RUN		apk add --no-cache openrc nginx openssl openssh && \
		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

# Create ssl key
RUN 	openssl req -x509 -nodes -days 365 -subj "/C=HA/ST=NH/O=Codam, Inc./CN=localhost" -addext "subjectAltName=DNS:localhost" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

# Remove old config and configure new nginx
RUN		rm /etc/nginx/conf.d/default.conf && \
		rm /etc/nginx/nginx.conf && \
		mkdir -p /run/nginx && \
 		mkdir -p /run/openrc/ && \
		mkdir -p /www && \
		mkdir -p /etc/telegraf

# Copy files into container
COPY 	./nginx.conf /etc/nginx/nginx.conf
COPY 	./nginx.conf /etc/nginx/conf.d/default.conf
COPY	./nginx_setup.sh ./nginx_setup.sh
COPY	./index.html /www/index.html
COPY	./telegraf.conf etc/telegraf/telegraf.conf

# Add user, password and generate ssh
RUN 	rc-update add sshd && \
		adduser -D -g 'www' www && \
		echo "www:password" | chpasswd && \
		ssh-keygen -A

# Give permissions
RUN		chown -R www:www /var/lib/nginx && \
		chown -R www:www /www && \
		chmod 755 nginx_setup.sh

# Listen on ports 80 443 22
EXPOSE	80 443 22

# Run nginx
CMD		[ "bin/sh", "nginx_setup.sh" ]